doctrine_mongodb:
    connections:
        default:
            server: "mongodb://mongodb:27017" # Utilise l'adresse du conteneur MongoDB
            options: {}
    default_database: "db_gamestore" # Assure-toi que le nom de la BDD est bien défini

    document_managers:
        default:
            auto_mapping: true
            # Cache de métadonnées
            metadata_cache_driver:
                type: array
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App

# Configuration pour l'environnement de test
when@test:
    doctrine_mongodb:
        connections:
            default:
                server: "mongodb://mongodb:27017"
                options: {}
        default_database: "db_gamestore_test" # BDD pour les tests
        document_managers:
            default:
                auto_mapping: true
                metadata_cache_driver:
                    type: array

# Configuration pour l'environnement de production
when@prod:
    doctrine_mongodb:
        document_managers:
            default:
                auto_generate_proxy_classes: false
                metadata_cache_driver:
                    type: redis
                    host: "%env(REDIS_HOST)%"
                    port: "%env(REDIS_PORT)%"
                proxy_dir: '%kernel.cache_dir%/doctrine/odm/proxies'
                query_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool