framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
    csrf_protection: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    form: true
    http_method_override: true
    assets: true
 # Définit un fallback statique au lieu de '%locale%'
    default_locale: 'en'  # Utilise une locale par défaut comme 'en' ou 'fr'