framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
        enabled: true  # Garde cela pour que le router soit activé
    csrf_protection: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    form: true
    http_method_override: true
    assets: true
    default_locale: 'en'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
    validation: true
    # Retirer cette partie car les annotations via doctrine ne sont plus supportées
    # annotations:
    #     enabled: true
    serializer: true