security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
        App\Entity\Employee:
            algorithm: bcrypt
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        employee_provider:
            entity:
                class: App\Entity\Employee
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            logout:
                path: app_logout
                target: app_homepage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true
                secure: auto
                httponly: true

        employee_area:
            provider: employee_provider  # Le bon provider pour l'Employee
            pattern: ^/employee
            custom_authenticator: App\Security\UserAuthenticator  # Utilisation du même authenticator pour l'Employee
            logout:
                path: employee_logout
                target: employee_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true
                secure: auto
                httponly: true

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/accueil$, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/achat, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/employee, roles: ROLE_EMPLOYEE }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER