framework:
    validation:
        auto_mapping:
            App\Entity\: true

        not_compromised_password: false

        # Ajouter un fichier de validation spécifique pour l'entité User
        mapping:
            paths:
                - '%kernel.project_dir%/config/validation/user.yaml'