services:
  # MySQL Database service
  database:
    image: mysql:8.0
    container_name: mysql_gamestore
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P 3306 --silent"]
      interval: 10s
      retries: 5
      timeout: 2s
      start_period: 30s
    networks:
     - app-network

  # PhpMyAdmin service for managing the database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gamestore
    environment:
      PMA_HOST: database
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
     - app-network

  # Symfony application service
  my_symfony_app:
    build: .
    container_name: my_symfony_app
    user: www-data
    volumes:
      - .:/var/www/html:rw,cached
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}?serverVersion=8.0
    networks:
     - app-network
    command: /bin/bash -c "tail -f /dev/null"
    # Attendre que la base de données soit prête avant de démarrer Symfony
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  database_data: