version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_gamestore
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sf_gamestore
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P 3306 --silent"]
      interval: 10s
      retries: 5
      timeout: 2s
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gamestore
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: userpassword
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  database_data: