version: '3.8'

services:
  # MySQL Database service
  database:
    image: mysql:8.0
    container_name: mysql_gamestore
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h database --silent"]
      interval: 10s
      retries: 5
      timeout: 2s
      start_period: 30s
    networks:
      - app-network

  # PhpMyAdmin service for managing the database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gamestore
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - app-network

  # Symfony application service
  my_symfony_app:
    build: .
    container_name: my_symfony_app
    user: www-data
    volumes:
      - .:/var/www/html:rw,cached
      - ./config/apache/apache-vhost.conf:/etc/apache2/sites-available/000-default.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - database
      - mongodb
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}?serverVersion=8.0
      - MONGODB_URL=mongodb://mongodb:27017
    networks:
     - app-network
    command: /usr/sbin/apache2ctl -D FOREGROUND
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb_gamestore
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/mongod.conf:/etc/mongod.conf
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database_data:
  mongo_data:
