parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Ajout explicite de CommandSyncService pour éviter les erreurs de casse
    App\Service\CommandSyncService:
        autowire: true
        autoconfigure: true
        public: false

    # Configuration pour l'Event Subscriber CartSubscriber
    App\EventSubscriber\CartSubscriber:
        arguments:
            $cartRepository: '@App\Repository\CartJeuxVideosRepository'
        tags:
            - { name: 'kernel.event_subscriber' }

    # Connexion MongoDB ODM
    doctrine_mongodb.odm.document_manager:
        class: Doctrine\ODM\MongoDB\DocumentManager
        factory: ['Doctrine\ODM\MongoDB\DocumentManager', 'create']
        arguments:
            - '@doctrine_mongodb.odm.connection'
            - '@doctrine_mongodb.odm.configuration'
            - '@doctrine_mongodb.odm.event_manager'

    doctrine_mongodb.odm.connection:
        class: MongoDB\Client
        arguments:
            - '%env(MONGODB_URL)%'

    doctrine_mongodb.odm.configuration:
        class: Doctrine\ODM\MongoDB\Configuration
        calls:
            - [setDefaultDB, ['%env(MONGODB_DB)%']]
            - [setMetadataDriverImpl, ['@doctrine_mongodb.odm.metadata_driver']]
            - [setHydratorDir, ['%kernel.cache_dir%/doctrine/odm/hydrators']]
            - [setHydratorNamespace, ['Hydrators']]

    # Pour l'utilisation des attributes
    doctrine_mongodb.odm.metadata_driver:
        class: Doctrine\ODM\MongoDB\Mapping\Driver\AttributeDriver
        arguments:
            - ['%kernel.project_dir%/src/Document']

    doctrine_mongodb.odm.event_manager:
        class: Doctrine\Common\EventManager

    # Exemple d'Event Manager pour MongoDB si nécessaire
    App\EventSubscriber\SomeOtherSubscriber:
        tags:
            - { name: 'doctrine_mongodb.odm.event_subscriber', event: 'some_event' }

    # LoginRedirectListener configuration pour la redirection après login
    App\EventListener\LoginRedirectListener:
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onSecurityInteractiveLogin' }

    # RedirectAdminListener configuration pour rediriger les administrateurs
    App\EventListener\RedirectAdminListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }

    # RedirectEmployeeListener configuration pour rediriger les employés
    App\EventListener\RedirectEmployeeListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }