App\Entity\User:
    properties:
        email:
            - NotBlank: { message: "L'adresse e-mail ne peut pas être vide." }
            - Email: { message: "L'adresse e-mail '{{ value }}' n'est pas valide." }

        password:
            - NotBlank: { message: "Le mot de passe ne peut pas être vide." }
            - Length:
                min: 8
                minMessage: "Le mot de passe doit contenir au moins {{ limit }} caractères."
                max: 4096
            - Regex:
                pattern: "/[A-Z]/"
                message: "Le mot de passe doit contenir au moins une lettre majuscule."
            - Regex:
                pattern: "/[a-z]/"
                message: "Le mot de passe doit contenir au moins une lettre minuscule."
            - Regex:
                pattern: "/[0-9]/"
                message: "Le mot de passe doit contenir au moins un chiffre."
            - Regex:
                pattern: "/[^\\w]/"
                message: "Le mot de passe doit contenir au moins un caractère spécial."